### ISSUE TITLE
Another strange issue

### ISSUE THREAD

**Issue by crazedVic** [redbastie/skele#2]
running skele:crud

Object of class Illuminate\Support\Stringable could not be converted to int

C:\Users\user\projects\dio-skele\vendor\redbastie\skele\src\Commands\CrudCommand.php:27
      Illuminate\Support\Str::replaceLast()

Doesn't seem to like $modelParser->className() as it returns instance of Illuminate\Support\Stringable instead of a string.

I was able to get this to work by changing it to:

```
$componentClass = Str::replaceLast((string)$modelParser->className(), Str::studly($modelTitles), $this->argument('class'));
```

**Comment by redbastie** [comment]
I'm working on windows fixes right now. Theres a bunch of stuff I need to fix.

**Comment by crazedVic** [comment]
> I'm working on windows fixes right now. Theres a bunch of stuff I need to fix.

just letting you know.  wasn't sure if this was OS related.

**Comment by redbastie** [comment]
I'm not sure it is OS related. I've no idea why you got that type error. I need a bit more time.

**Comment by crazedVic** [comment]
I'm done the video, you want me to test tailwire now or wait until you commit all the fixes you're working on now?

**Comment by redbastie** [comment]
Test tailwire, but in your fork of tailwire, try this first:

In the `ManagesFiles` class, try replacing this:

    $filePath = Str::replaceLast('.stub', '', $this->replace($replaces, $file->getRelativePathname()));

    if ($fileDir = implode('/', array_slice(explode('/', $filePath), 0, -1))) {
        $this->filesystem()->ensureDirectoryExists($fileDir);
    }

With this:

	$filePath = Str::replaceLast('.stub', '', $this->replace($replaces, $file->getRelativePathname()));
	$filePath = str_replace('/', DIRECTORY_SEPARATOR, $filePath);

    if ($fileDir = implode(DIRECTORY_SEPARATOR, array_slice(explode(DIRECTORY_SEPARATOR, $filePath), 0, -1))) {
        $this->filesystem()->ensureDirectoryExists($fileDir);
    }

Then you should be able to undo all other changes you made, as it's replacing the separator for every single file that gets made.

Let me know how this works. I'm having a hell of a time using Windows in parallel.

**Comment by crazedVic** [comment]
Ok i'm on it.  tailwire:install failed right out of the box (unlike skele) but then i made the above change and it worked.  will keep you posted, will continue reporting going forward in the tailwire repo.

**Comment by redbastie** [comment]
OK. In tailwire, are you getting that string error too?

**Comment by redbastie** [comment]
Yes please make an issue in tailwire repo. Thank you.
